
services:
  web:
    container_name: flask_name
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: